#
# ci.yml
#
# Run tests for all pushed commits and opened pull requests on Github.
#

name: CI
on: [push, pull_request]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Git checkout
        uses: actions/checkout@v2
      - name: NPM ci, build, & test
        run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Git checkout
        uses: actions/checkout@v2
      - name: NPM ci, build, & test
        run: |
          npm ci
          npm run build --if-present
          npm run build && node --enable-source-maps --stack-trace-limit=1000 ./build/src/examples/smart_contract.js
        env:
          CI: true
